services: docker

before_install:
  - docker -v
  - cp example.env .env
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - docker-compose up -d

script:
  - docker-compose -f docker-compose.travis.yml up --build --abort-on-container-exit