version: '3'
services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile 
      args:
        port: ${PORT}
    env_file:
      - .env
    expose:
      - ${PORT}
    links:
      - database
  database:
    image: mongo:4.0
    env_file:
      - .env
    volumes:
      - ".${MONGO_DATA_DIR}":${MONGO_DATA_DIR}
    expose:
      - 27017
    command: mongod --smallfiles